### ISSUE TITLE
Iconography page displays horizontal scroll bar in certain icon categories 

### ISSUE THREAD

**Issue by jeffvg** [pxblue/doc-it#135]
#### Describe the bug
Expanding the A, M or S icon categories using internet explorer displays horizontal scroll bar. If you toggle hide material icons the scroll bar is removed 

#### What is the expected behavior?
No horizontal scroll bar in any category

#### What are the steps to reproduce?
1. Go to https://pxblue.github.io/style/iconography
2. Click on A, M or S category to expand icon list
3. Observe horizontal scroll bar

#### What is your environment?

 Framework
- [ ] Angular
- [X] React
- [ ] Ionic
- [ ] React Native

 Browser
- [X] Internet Explorer
- [ ] Edge
- [ ] Safari
- [ ] Chrome
- [ ] Firefox

 Operating System
- [ ] MacOS
- [X] Windows
- [ ] Other

**Comment by huayunh** [comment]
Does this still apply in the latest iconography page? @jeffvg

**Comment by jeffvg** [comment]
This is no longer exists since re-design of page. Closing this issue
