### ISSUE TITLE
Iconography icon details bottom sheet opens behind window in portrait view mobile.

### ISSUE THREAD

**Issue by jeffvg** [pxblue/doc-it#150]
#### Describe the bug
Iconography icon details bottom sheet opens behind window in portrait view.
Rotating to landscape displays bottom sheet but only the main div and close/open buttons.
Bottom sheet header, Icon font and SVG tabs not displayed.
#### What is the expected behavior?
Scrolling on bottom sheet to display entire view
#### What are the steps to reproduce?
1. Go to https://pxblue.github.io/style/iconography on mobile device
2. Click on any icon to view details
3. Bottom sheet not displayed
4. Rotate to landscape
5. Bottom sheet displays (only main div and buttons) 

#### Screenshots or links to minimum reproduction example
![bottomsheet](https://user-images.githubusercontent.com/37150565/78394925-82f9d780-75ba-11ea-88b0-a0c32f4f4237.jpg)

#### What is your environment?

 Framework
- [ ] Angular
- [X] React
- [ ] Ionic
- [ ] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [X] Chrome
- [ ] Firefox

 Operating System
- [ ] MacOS
- [ ] Windows
- [X] Other
		
#### Anything else to add?
Android/iPhone mobile device or xs small view in browser

**Comment by andrupu** [comment]
Put a max-height on the bottomsheet so that is has a scrollbar.
