### ISSUE TITLE
Design Patterns page pattern cards wider than view port

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#152]
#### Describe the bug
On the design patterns page, when your viewport is small enough (maybe smaller than 1200px wide), if you scroll horizontally to the right you will see a small 9px-wide stripe. This is likely caused by the pattern cards 

#### What is the expected behavior?
There should be no stripes

#### What are the steps to reproduce?
1. Go to https://pxblue.github.io/patterns
2. Ensure your viewport window is less than 1000px(?)
3. Try scrolling to the right

#### Screenshots or links to minimum reproduction example
(see the top right corner)
![image](https://user-images.githubusercontent.com/8997218/78459265-d422cd80-7685-11ea-88e4-59e51acb2879.png)

#### What is your environment?
iPhone Safari and Mac chrome
		
#### Anything else to add?
A cosmetic issue... just annoying.

**Comment by joebochill** [comment]
I think the margin->padding fix in the latest react drawerlayout component will fix this.

**Comment by andrupu** [comment]
Update doc-it to use latest component library and verify if this fixes it.
