### ISSUE TITLE
Need to escape asterisk sign * in the markdown

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#197]
#### Describe the bug

https://px-blue.github.io/patterns/forms
asterisk signs are interpreted as the italics mark

#### What is the expected behavior?
Should be escaped

#### What are the steps to reproduce?
1. Go to https://px-blue.github.io/patterns/forms
2. Check the Optional vs. Required Fields section

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/8997218/84082160-5c3a9180-a9ad-11ea-8e15-232580fbb4e7.png)

#### Anything else to add?
I only noticed this one, but there might be other ones somewhere

**Comment by joebochill** [comment]
This one is not an asterisk at all...looks like prettier converted it to underscore?
![image](https://user-images.githubusercontent.com/29152776/85547987-777fe080-b5ec-11ea-95de-e5f0d24e852a.png)
![image](https://user-images.githubusercontent.com/29152776/85548882-65eb0880-b5ed-11ea-91a5-612bef237f7d.png)

**Comment by joebochill** [comment]
I did a few global searches and this looks like it is the only instance where this has occurred.
