### ISSUE TITLE
Release notes need their own heading deeplink system

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#220]
#### Describe the desired behavior

In the release notes page, implement a component that allows deep linking into all the H1's (and only the H1's). So H2, H3... should not copy anything to the clipboard on click, and all the H1 will copy the hash.

#### Describe the current behavior

Release notes page:
1. does not allow deep link or display the link icon for the first H1
2. has headlines sharing the same title

**Comment by jeffvg** [comment]
moved to PXBLUE-1908
