### ISSUE TITLE
Iconography page's icon browser should expand on search

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#228]
#### Describe the desired behavior

When the user does a search (or land on the page via deep link), the iconography's icon browser should expand all the sections. 

#### Describe the current behavior

It doesn't

**Comment by joebochill** [comment]
Might be nice to also add an empty state when there are no results

**Comment by huayunh** [comment]
Might be removed with the current page design

**Comment by joebochill** [comment]
The new design preferred approach will be to have a flat list without expandable sections, so this will no longer be a concern.
