### ISSUE TITLE
TOC for long pages

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#256]
## Describe the desired behavior

I want a table of content for loooong pages (#254 is currently 19648 px tall on desktops)

## Describe the current behavior

I tried doing 
```md
-   [Common Use Cases](#common-use-cases)
-   [Variations](#variations)
-   [Behaviors](#behaviors)
-   [Design Specifications](#design-specifications)
-   [Developers](#developers)
```

But it doesn't work. 

## Is this request related to a current issue?
No

## Additional Context
Deeplinking itself is still working, but it looks like when you have an internal link pointing to its own path, react router simply won't trigger anything.

**Comment by jeffvg** [comment]
Look in to react router and see if there are any open issues on this. 
Look in to our scroll to top behavior we currently have.

**Comment by huayunh** [comment]
In case anyone's curious, the page pxblue.github.io/patterns/lists is currently at 20023.1 px tall.

Request for a ToC has been around the first time I refactored the form validation pattern

**Comment by huayunh** [comment]
Hmm… might want to extend the stale markers

I suggest extend those to one quarter (bc we do bug squash every quarter)

**Comment by joebochill** [comment]
I bumped up the stalebot to 90 days for the first warning (still have 10 days after that to respond to keep it open).
