### ISSUE TITLE
Icon Meta Data should be loaded at runtime

### ISSUE THREAD

**Issue by joebochill** [pxblue/doc-it#297]
#### Describe the desired behavior
The latest material icon metadata should be fetched from the API when the application loads.

#### Describe the current behavior
We have a hardcoded metadata file that will become obsolete whenever material updates their icons.

#### Is this request related to a current issue?
Not yet, but it was identified during the iconography page design update.

#### Additional Context

The file from the API call is slightly malformed and needs to be cleaned up before it is usable json. If you refer to the code that MUI uses when they create their icon library, you can see the couple of steps needed to sanitize it.

**Comment by joebochill** [comment]
Don't delete this!

**Comment by jeffvg** [comment]
moved to PXBLUE-1907

**Comment by emclaug2** [comment]
Where's the link?
