### ISSUE TITLE
Rewrite the theme logic using hooks

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#315]
#### Describe the desired behavior

Wrap the switch theme logic inside a custom hook so that the for loop does not run on every render

#### Describe the current behavior

The sync function `getScheduledSiteConfig` gets executed every time the page get's re-rendered

#### Is this request related to a current issue?

NO

#### Additional Context

To avoid "a flash of the default blue theme" before switching to the desired theme, I suggest putting something in the local storage. So that when the user starts their session it checks for any existing theme and loads that one first.

**Comment by jeffvg** [comment]
moved to PXBLUE-1906
