### ISSUE TITLE
Resource Page Package Info is Outdated

### ISSUE THREAD

**Issue by emclaug2** [pxblue/doc-it#325]
#### Describe the bug
The resources listed on this page have latest version numbers for each package; these versions are out of date.
https://pxblue.github.io/resources

#### What is the expected behavior?
Each version number should be the latest.

#### What are the steps to reproduce?
Go here: https://pxblue.github.io/resources
Look at the @pxblue/angular-components
Latest version should be ^4.0.0

#### Environment

Windows/Chrome

**Comment by emclaug2** [comment]
This seems to be related: https://github.com/npms-io/npms-api/issues/101

**Comment by joebochill** [comment]
Looks like this has resolved itself...probably something to do with how often they are pulling fresh data from npm.
