### ISSUE TITLE
Load Roadmap Databases individually for each release

### ISSUE THREAD

**Issue by joebochill** [pxblue/doc-it#333]
#### Describe the desired behavior
When a user selects "R17" from the release dropdown on the roadmap page, call the roadmap API to load the R17 roadmap file. When they select "R19" make another call and load the R19 roadmap file.

#### Describe the current behavior
Currently we make a single call to load the latest roadmap file. This roadmap file also contains/duplicates all of the data from the previous releases.

#### Is this request related to a current issue?
Not related to a current issue, but we're running into the situation where:
1) It's getting difficult to read the latest roadmap database file because there is so much extra data in it
2) The data fetched over HTTP is going to continue to grow and grow every release and may cause performance issues down the line.

#### Additional Context
We should be able to dynamically load new data (and show the placeholder skeletons while we fetch it) when the user chooses a different release from the dropdown. Once we do that, we should be able to clean up the roadmap database files to only include the items that are in that release (and we will need to add an N+1 release file in order to show the mini preview of what will be coming in the release after the current one).

**Comment by emclaug2** [comment]
The dropdown option for 'ALL RELEASES' should be removed from doc-it when we make this change.

**Comment by jeffvg** [comment]
moved PXBLUE-1905
