### ISSUE TITLE
Deep linking to an icon should cause the page to scroll to that icon on load

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#354]
#### Describe the desired behavior

When deep linking into an icon, the iconography page should scroll down to where that icon is selected

#### Describe the current behavior

It doesn't go anywhere right now at the moment

**Comment by jeffvg** [comment]
Research how Material does this with query strings or
Look at how we did this for table of contents for a potential solution using set timeout to wait for icons to load

**Comment by jeffvg** [comment]
moved - PXBLUE-1904
