### ISSUE TITLE
Add Brightlayer designation

### ISSUE THREAD

**Issue by joebochill** [pxblue/doc-it#387]
#### Describe the desired behavior
Would like to have some sort of indicator that PX Blue is part of Brightlayer.

#### Describe the current behavior
No indication.

#### Is this request related to a current issue?
This is related to the current work to rebrand the platforms under the Brightlayer umbrella.

#### Additional Context

This could be something in the footer, the landing banner, etc. Might be worthwhile coming up with a few different concepts and review them to see what we like best.

**Comment by huayunh** [comment]
Closing the issue as it will be addressed during BLUI migration stories.
