### ISSUE TITLE
Community icons are shifted upwards

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#393]
#### Describe the bug

In `/community`, the icons in the info cards are top-aligned

#### What is the expected behavior?

Icons should be centered

#### What are the steps to reproduce?
1. Go to https://pxblue.github.io/community
2. Observe that the icon styles are a bit wrong

#### Screenshots or links to minimum reproduction example

This `<span>` would appreciate a `display:flex`
![image](https://user-images.githubusercontent.com/8997218/115247781-171adc00-a0f5-11eb-8928-329c972fb122.png)

**Comment by joebochill** [comment]
This might be related to when we switched over to rems since the size is explicitly set in px. Should be an easy fix with the flexbox props.
