### ISSUE TITLE
Bug counts are wrong for themes on resources

### ISSUE THREAD

**Issue by joebochill** [pxblue/doc-it#403]
#### Describe the bug
The resources page shows the incorrect number of bugs on the themes packages. They are reporting the total number of bugs in the themes mono repo instead of framework specific counts.

#### What is the expected behavior?
These should be reporting bugs only with the specific framework label.

#### What are the steps to reproduce?
1. Go to doc-it resources page
2. Look at the themes packages...they all have the same count (they're only looking at the bug label)

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/117031376-833d3880-acce-11eb-9fd8-9ed4d31edf95.png)

**Comment by emclaug2** [comment]
I started looking into this issue but it's annoying to fix because I cannot get the badges to load locally.

**Comment by huayunh** [comment]
It appears this has been fixed with the themes repo migration. Closing the issue.
