### ISSUE TITLE
ng design pattern links should not point to dev

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#435]
#### Describe the bug

Angular design pattern links are currently pointing to dev

#### What is the expected behavior?

Should point to master

#### What are the steps to reproduce?
1. Go to https://pxblue.github.io/patterns/appbar#basic-app-bar 
2. Click on any chip buttons

**Comment by joebochill** [comment]
This will need to be updated for all of the frameworks. The default branch on github is dev, so links that don't specify a branch will always go to dev. We will need to update the links to include `/tree/master` to point to the specific branch.

**Comment by huayunh** [comment]
Can verify that all links are currently pointing to master
