### ISSUE TITLE
Update list patterns to include an example of those "inline list editing"

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#438]
#### Describe the desired behavior

Talk about this: 
![image](https://user-images.githubusercontent.com/8997218/125103583-7eb84600-e0aa-11eb-96cf-906288772203.png)

#### Describe the current behavior

It does not say anything

#### Additional Context

Green Motion folks were confused over the use of this.

**Comment by daileytj** [comment]
Add this to the list pattern description.
