### ISSUE TITLE
Navigation drawer onBackdropClick forward ref deprecated

### ISSUE THREAD

**Issue by jeffvg** [pxblue/doc-it#484]
#### Describe the bug
recent changes in material-ui/core @4.12.3 has caused deprecation warning for drawer props and when doc'it starts it displays this warning.
- Warning: Failed prop type: The prop `onBackdropClick` of `ForwardRef(Modal)` is deprecated. Use the onClose prop with the `reason` argument to handle the `backdropClick` events.

#### What is the expected behavior?
No deprecation warnings
#### What are the steps to reproduce?
1. clone doc'it dev
2. yarn && yarn start

#### Anything else to add?
![image](https://user-images.githubusercontent.com/37150565/144447019-dbfa159d-a99a-457a-9292-b6f82e639829.png)

**Comment by emclaug2** [comment]
This will be an actual error when we start using material ui v5.
