### ISSUE TITLE
Deprecation warning noticed on inner sourcing page

### ISSUE THREAD

**Issue by jeffvg** [pxblue/doc-it#485]
#### Describe the bug
Navigating to inner source page throws dep warning. http://localhost:3000/community/innersourcing
- Warning: Failed prop type: The prop `justify` of `ForwardRef(Grid)` is deprecated. Use `justifyContent` instead, the prop was renamed
- material-ui v 4.12.3 has styling prop changes

#### What is the expected behavior?
no warning
#### What are the steps to reproduce?
1. clone doc'it dev
2. yarn && yarn start
3.  http://localhost:3000/community/innersourcing

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/144448703-86ec9296-9f0b-4521-8f63-94105a45972d.png)

**Comment by emclaug2** [comment]
This is only observed locally; must rename a prop.
